### ISSUE TITLE
Recommendation: move the UNUSED macro to aria.h

### ISSUE THREAD

**Issue by jason-c-daniels** [rxi/aria#3]
**Use Case**
The consuming developer wishes to embed an aria console in their application, modeled on the sample main function.

**Estimated Impact**
_Cons:_ Potential for human error during copy and paste.
_Pros:_ It keeps the coding style neat and consistent with the rest of aria and provides an "out of the box" compilable solution for beginning programmers who want to start extending and embedding aria in another application.

**Comment by rxi** [comment]
The `UNUSED` macro is intentionally internal as projects which have unused-variable warnings enabled will likely be using their own unused-macro, those that don't wouldn't require such a macro. I'm not sure I understand the benefit of moving it to the header file.

**Comment by jason-c-daniels** [comment]
I guess I misunderstood the purpose of that macro. I thought it was more important than it was. :-)
